### ISSUE TITLE
Outdated version 1.2.0 on haxelib 

### ISSUE THREAD

**Issue by jonasmalacofilho** [ypid/haxe-version#4]
See: https://lib.haxe.org/p/version

I assume you're still having [issues with your password](https://github.com/ypid/haxe-version/pull/3#issuecomment-463837702)...

Didn't you get a reply from Andy Li?  You can also try opening an issue on [HaxeFoundation/haxelib](https://github.com/HaxeFoundation/haxelib).

**Comment by ypid** [comment]
Did not have the time yet. I will look into it within one week hopefully.

**Comment by jonasmalacofilho** [comment]
Ping @ypid.

**Comment by ypid** [comment]
Hi, sorry for the unresponsiveness. I am too overloaded to look into this in the next time. I have not touched Haxe for years. Still find it interesting but I am maintaining a few other projects that also fight for my resources. I would be very happy to pass maintenance over to someone more involved. Is that possible?

**Comment by jonasmalacofilho** [comment]
Sure, I can take over here.  While a small library, it's pretty useful.

My username there is the same: `jonasmalacofilho`.

**Comment by ypid** [comment]
For reference, I wrote a new password MD5 hash to contact@haxe.org on 2020-06-26 after getting a bit into Haxe and the ecosystem again. Enough to pass on maintainership for now. No answer yet.

**Comment by jonasmalacofilho** [comment]
Thanks for the update.

You can also try directly c/c'ing @andyli on the new hash, because I'm not sure if he has access to contact@haxe.org.

> Send me an email (address can be found on my profile) with the md5 hash of your new password. Make sure the password you choose is not used by any of your other accounts...
> —_https://github.com/HaxeFoundation/haxelib/issues/415#issuecomment-376502746_

**Comment by ypid** [comment]
Thanks for the prompt answer @andyli. All that delay is on me and I am sorry for that. I followed the FAQ and added @jonasmalacofilho as contributor and made a new release (v1.3.1) and submitted it to lib.haxe.org. You should now have write access. Additionally, I give you write access to this repository here. If you want to use it or just fork it and take over is up to you. I only have one wish, don’t rewrite the git history because that would destroy my OpenPGP signatures :)

Do you need anything else?

Ref: https://lib.haxe.org/p/version

**Comment by jonasmalacofilho** [comment]
No, that's all.  Thank you again!

**Comment by ypid** [comment]
You are welcome :)
